COPTS = [
    "-std=c++14",
    "-Werror",
]

cc_library (
    name = "stream",
    hdrs = ["stream.hpp", "logger.hpp"],
    srcs = ["stream.cpp"],
    visibility = ["//test:__pkg__"],
    copts = COPTS,
)
